// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ctdjqbxphvktymbrxkcs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN0ZGpxYnhwaHZrdHltYnJ4a2NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2MTU0NTYsImV4cCI6MjA2NzE5MTQ1Nn0.zkSy1XMaN8CxogBq9nXNoNzjT897skxd71WrjIAYJto";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);